algorithms:
#  - first_fit
#  - shelf_bwf
#  - shelf_bfdh
  - shelf_floor_ceil
  - maxrects

#input_file: ../input/big_polygon_input.json
input_file: ../input/input2.json
#input_file: ../input/input1.json
